[tool.poetry]
name = "advent-of-code"
version = "0.1.0"
description = ""
authors = ["reyley <rachel.ilan@uplight.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
ortools = "^9.8.3296"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
